### ISSUE TITLE
Raspberry Pi as gateway via dnsmasq

### ISSUE THREAD

**Issue by alexose** [FreshXOpenSource/melnor_decloudify#3]
An alternative approach that might work better for some folks is to plug the Melnor unit directly into a Raspberry Pi running this application, and then use dnsmasq to redirect `ws.pusherapp.com` and `wifiaquatimer.com`.

I was able to do this by following [this guide](https://forums.raspberrypi.com/viewtopic.php?t=132674) but instead using the following /etc/dnsmasq.conf config:
```
interface=eth0
listen-address=172.24.1.1
bind-interfaces
server=8.8.8.8
domain-needed
bogus-priv
dhcp-range=172.24.1.50,172.24.1.150,12h
host-record=ws.pusherapp.com,172.24.1.1
host-record=wifiaquatimer.com,172.24.1.1
```

I then commented out `dns.start()` in actor.js and ran `sudo node actor.js`. Requests seem to be coming in properly.

Might be good to support this setup, as I think it's a better approach for those of us with an extra Pi laying around.  I used an ancient Pi 1 that was otherwise just gathering dust.

**Comment by fxkai** [comment]
@alexose thats nice and would help us to run as a random user instead of root, since we dont need to bind :53 anymore

**Comment by fxkai** [comment]
is now supported via settings. documented also in README.
