### ISSUE TITLE
Will melnor_decloudify still work when Melnor stops supporting the timer altogether?

### ISSUE THREAD

**Issue by arigoldx** [FreshXOpenSource/melnor_decloudify#4]
I've been looking for a way to keep my three wifi Melnor wifi timers functional after Melnor stops supporting wifiaquatimer.com

There are a few open source libraries out there. There might be more but so far I've found:

https://github.com/jpjodoin/sunshower
https://github.com/vanstinator/raincloudy

and, of course,

https://github.com/FreshX-GmbH/melnor_decloudify

Y'all are the most recently committed so I thought I'd check in.

Is there anything about the tech stack that would break when wifiaquatimer.com goes away?

Or should follow the README and get these things working? :)

Thanks for y'alls time!

**Comment by FreshXOpenSource** [comment]
Hi @arigoldx,

unfortunately my Melnor got busted this winter due to frozen water 🙈.

Still, technologically it should not matter if the domains disappear, since we create our own DNS Server and fake their entries without asking upstream.

If not, please let us know.

**Comment by arigoldx** [comment]
Just an FYI that I recently asked Melnor for an end date on the RainCloud and was told that they're going to extend support for the server until _the new model is released_!

Pretty cool that they're going to have a new "upgraded" (🤞) model. On the one hand, there's still a need for this since they'll probably break the server. ¯\\\_(ツ)\_/¯
